const molecules = [
  {name:"Water", formula:"H2O", type:"Inorganic"},
  {name:"Hydrogen", formula:"H2", type:"Element"},
  {name:"Oxygen", formula:"O2", type:"Element"},
  {name:"Nitrogen", formula:"N2", type:"Element"},
  {name:"Ozone", formula:"O3", type:"Element"},
  {name:"Carbon Dioxide", formula:"CO2", type:"Inorganic"},
  {name:"Carbon Monoxide", formula:"CO", type:"Inorganic"},
  {name:"Ammonia", formula:"NH3", type:"Inorganic"},
  {name:"Methane", formula:"CH4", type:"Organic"},
  {name:"Ethane", formula:"C2H6", type:"Organic"},
  {name:"Propane", formula:"C3H8", type:"Organic"},
  {name:"Butane", formula:"C4H10", type:"Organic"},
  {name:"Pentane", formula:"C5H12", type:"Organic"},
  {name:"Hexane", formula:"C6H14", type:"Organic"},
  {name:"Heptane", formula:"C7H16", type:"Organic"},
  {name:"Octane", formula:"C8H18", type:"Organic"},
  {name:"Ethanol", formula:"C2H6O", type:"Organic"},
  {name:"Methanol", formula:"CH4O", type:"Organic"},
  {name:"Propanol", formula:"C3H8O", type:"Organic"},
  {name:"Acetone", formula:"C3H6O", type:"Organic"},
  {name:"Glucose", formula:"C6H12O6", type:"Organic"},
  {name:"Fructose", formula:"C6H12O6", type:"Organic"},
  {name:"Sucrose", formula:"C12H22O11", type:"Organic"},
  {name:"Lactose", formula:"C12H22O11", type:"Organic"},
  {name:"Maltose", formula:"C12H22O11", type:"Organic"},
  {name:"Caffeine", formula:"C8H10N4O2", type:"Organic"},
  {name:"Urea", formula:"CH4N2O", type:"Organic"},
  {name:"Benzene", formula:"C6H6", type:"Organic"},
  {name:"Toluene", formula:"C7H8", type:"Organic"},
  {name:"Phenol", formula:"C6H6O", type:"Organic"},
  {name:"Aniline", formula:"C6H7N", type:"Organic"},
  {name:"Acetic Acid", formula:"C2H4O2", type:"Organic"},
  {name:"Formic Acid", formula:"CH2O2", type:"Organic"},
  {name:"Citric Acid", formula:"C6H8O7", type:"Organic"},
  {name:"Lactic Acid", formula:"C3H6O3", type:"Organic"},
  {name:"Oxalic Acid", formula:"C2H2O4", type:"Organic"},
  {name:"Benzoic Acid", formula:"C7H6O2", type:"Organic"},
  {name:"Salicylic Acid", formula:"C7H6O3", type:"Organic"},
  {name:"Aspirin", formula:"C9H8O4", type:"Organic"},
  {name:"Acetylene", formula:"C2H2", type:"Organic"},
  {name:"Ethylene", formula:"C2H4", type:"Organic"},
  {name:"Propene", formula:"C3H6", type:"Organic"},
  {name:"Styrene", formula:"C8H8", type:"Organic"},
  {name:"Formaldehyde", formula:"CH2O", type:"Organic"},
  {name:"Acetaldehyde", formula:"C2H4O", type:"Organic"},
  {name:"Chloroform", formula:"CHCl3", type:"Organic"},
  {name:"Carbon Tetrachloride", formula:"CCl4", type:"Inorganic"},
  {name:"Hydrogen Peroxide", formula:"H2O2", type:"Inorganic"},
  {name:"Sulfuric Acid", formula:"H2SO4", type:"Acid"},
  {name:"Hydrochloric Acid", formula:"HCl", type:"Acid"},
  {name:"Nitric Acid", formula:"HNO3", type:"Acid"},
  {name:"Phosphoric Acid", formula:"H3PO4", type:"Acid"},
  {name:"Sulfurous Acid", formula:"H2SO3", type:"Acid"},
  {name:"Carbonic Acid", formula:"H2CO3", type:"Acid"},
  {name:"Sodium Hydroxide", formula:"NaOH", type:"Base"},
  {name:"Potassium Hydroxide", formula:"KOH", type:"Base"},
  {name:"Calcium Hydroxide", formula:"Ca(OH)2", type:"Base"},
  {name:"Magnesium Hydroxide", formula:"Mg(OH)2", type:"Base"},
  {name:"Sodium Chloride", formula:"NaCl", type:"Salt"},
  {name:"Potassium Chloride", formula:"KCl", type:"Salt"},
  {name:"Calcium Chloride", formula:"CaCl2", type:"Salt"},
  {name:"Magnesium Chloride", formula:"MgCl2", type:"Salt"},
  {name:"Sodium Carbonate", formula:"Na2CO3", type:"Salt"},
  {name:"Sodium Bicarbonate", formula:"NaHCO3", type:"Salt"},
  {name:"Calcium Carbonate", formula:"CaCO3", type:"Salt"},
  {name:"Magnesium Carbonate", formula:"MgCO3", type:"Salt"},
  {name:"Potassium Carbonate", formula:"K2CO3", type:"Salt"},
  {name:"Sodium Sulfate", formula:"Na2SO4", type:"Salt"},
  {name:"Potassium Sulfate", formula:"K2SO4", type:"Salt"},
  {name:"Calcium Sulfate", formula:"CaSO4", type:"Salt"},
  {name:"Copper Sulfate", formula:"CuSO4", type:"Salt"},
  {name:"Zinc Sulfate", formula:"ZnSO4", type:"Salt"},
  {name:"Iron Sulfate", formula:"FeSO4", type:"Salt"},
  {name:"Sodium Nitrate", formula:"NaNO3", type:"Salt"},
  {name:"Potassium Nitrate", formula:"KNO3", type:"Salt"},
  {name:"Calcium Nitrate", formula:"Ca(NO3)2", type:"Salt"},
  {name:"Silver Nitrate", formula:"AgNO3", type:"Salt"},
  {name:"Ammonium Chloride", formula:"NH4Cl", type:"Salt"},
  {name:"Ammonium Nitrate", formula:"NH4NO3", type:"Salt"},
  {name:"Ammonium Sulfate", formula:"(NH4)2SO4", type:"Salt"},
  {name:"Sodium Phosphate", formula:"Na3PO4", type:"Salt"},
  {name:"Calcium Phosphate", formula:"Ca3(PO4)2", type:"Salt"},
  {name:"Sodium Acetate", formula:"C2H3NaO2", type:"Salt"},
  {name:"Potassium Permanganate", formula:"KMnO4", type:"Salt"},
  {name:"Potassium Dichromate", formula:"K2Cr2O7", type:"Salt"},
  {name:"Sodium Hypochlorite", formula:"NaClO", type:"Salt"},
  {name:"Calcium Hypochlorite", formula:"Ca(ClO)2", type:"Salt"},
  {name:"Sulfur Dioxide", formula:"SO2", type:"Inorganic"},
  {name:"Sulfur Trioxide", formula:"SO3", type:"Inorganic"},
  {name:"Nitrogen Dioxide", formula:"NO2", type:"Inorganic"},
  {name:"Nitrous Oxide", formula:"N2O", type:"Inorganic"},
  {name:"Nitric Oxide", formula:"NO", type:"Inorganic"},
  {name:"Sulfur Hexafluoride", formula:"SF6", type:"Inorganic"},
  {name:"Silicon Dioxide", formula:"SiO2", type:"Inorganic"},
  {name:"Calcium Oxide", formula:"CaO", type:"Inorganic"},
  {name:"Magnesium Oxide", formula:"MgO", type:"Inorganic"},
  {name:"Aluminum Oxide", formula:"Al2O3", type:"Inorganic"},
  {name:"Iron Oxide", formula:"Fe2O3", type:"Inorganic"},
  {name:"Copper Oxide", formula:"CuO", type:"Inorganic"},
  {name:"Zinc Oxide", formula:"ZnO", type:"Inorganic"},
  {name:"Hydrogen Sulfide", formula:"H2S", type:"Inorganic"},
  {name:"Phosphine", formula:"PH3", type:"Inorganic"},
  {name:"Silane", formula:"SiH4", type:"Inorganic"},
  {name:"Dinitrogen Pentoxide", formula:"N2O5", type:"Inorganic"},
  {name:"Phosphorus Pentoxide", formula:"P2O5", type:"Inorganic"},
  {name:"Boron Trifluoride", formula:"BF3", type:"Inorganic"},
  {name:"Sulfur Hexafluoride", formula:"SF6", type:"Inorganic"},
  {name:"Ethylene Glycol", formula:"C2H6O2", type:"Organic"},
  {name:"Glycerol", formula:"C3H8O3", type:"Organic"},
  {name:"Diethyl Ether", formula:"C4H10O", type:"Organic"},
  {name:"Dimethyl Ether", formula:"C2H6O", type:"Organic"},
  {name:"Acetonitrile", formula:"C2H3N", type:"Organic"},
  {name:"Pyridine", formula:"C5H5N", type:"Organic"},
  {name:"Pyrrole", formula:"C4H5N", type:"Organic"},
  {name:"Imidazole", formula:"C3H4N2", type:"Organic"},
  {name:"Naphthalene", formula:"C10H8", type:"Organic"},
  {name:"Anthracene", formula:"C14H10", type:"Organic"},
  {name:"Glutamic Acid", formula:"C5H9NO4", type:"Organic"},
  {name:"Glycine", formula:"C2H5NO2", type:"Organic"},
  {name:"Alanine", formula:"C3H7NO2", type:"Organic"},
  {name:"Valine", formula:"C5H11NO2", type:"Organic"},
  {name:"Leucine", formula:"C6H13NO2", type:"Organic"},
  {name:"Lysine", formula:"C6H14N2O2", type:"Organic"}
];
